name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force: enable
          
      - name: ls
        run: |
          ls /home/runner/work/zowe-common-c/zowe-common-c/   
          echo "new"
          ls /home/runner/work/zowe-common-c/
          
      - name: upload to artifact      
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/zowe-common-c/zowe-common-c/cppcheck_report.txt
