name: cppcheck-action-test
on:
  push:
    branches:
      - v1.x/staging
      - master
      - rc
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: '[Prep 2] Setup jFrog CLI'
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
          
      - name: upload artifact      
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck_report.txt
          path: /home/runner/work/zowe-common-c/zowe-common-c/cppcheck_report.txt
          
