name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force: enable
          
      - name: upload to artifactory 
        run: |
          ls /home/runner/work/zowe-common-c/zowe-common-c/
          TIMESTAMP=`date +%Y%m%d.%H%M%S`
          mv cppcheck_report.txt cppcheck_report_${TIMESTAMP}.txt
          jfrog rt u cppcheck_report_${TIMESTAMP}.txt libs-snapshot-local/org/zowe/zlux/zowe-common-c/scan/cppcheck_report_${TIMESTAMP}.txt
          
