name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force: enable
          
      - name: upload artifact      
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck_report.txt
          path: /home/runner/work/zowe-common-c/zowe-common-c/cppcheck_report.txt
          
