name: Run test
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      - name: check permission
        uses: zowe-actions/shared-actions/permission-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  run-test:
    runs-on: windows-latest
    needs: check-permission
    steps: 
     
      - name: 'Set up Clang'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
     
      - name: 'Checkout zowe-common-c'
        uses: actions/checkout@v3
        with:
          path: zowe-common-c
        
      - name: 'Checkout Libyaml'
        uses: actions/checkout@v3
        with:
          repository: yaml/libyaml
          path: deps
          ref: '0.2.5'
      
      - name: 'Checkout Quickjs'
        uses: actions/checkout@v3
        with:
          repository: joenemo/quickjs-portable
          path: quickjs
          ref: 'main'
     
      - name: 'Running convtest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang -I../h -I../platform/windows -D_CRT_SECURE_NO_WARNINGS -Dstrdup=_strdup -DYAML_DECLARE_STATIC=1 -Wdeprecated-declarations --rtlib=compiler-rt -o convtest.exe convtest.c ../c/charsets.c ../platform/windows/winfile.c ../c/timeutls.c ../c/utils.c ../c/alloc.c
      
      - name: 'Running charsetguesser.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang -I../../deps/include -I./src -I../h -I ../platform/windows -Dstrdup=_strdup -D_CRT_SECURE_NO_WARNINGS -o charsetguesser.exe charsetguesser.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c 

      - name: 'run jqtest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang -I../platform/windows -I ..\h -Wdeprecated-declarations -D_CRT_SECURE_NO_WARNINGS -o jqtest.exe jqtest.c ../c/microjq.c ../c/parsetools.c ../c/json.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c
          
      - name: 'run jsonmergetest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang -I./src -I../h -I ../platform/windows -Dstrdup=_strdup -D_CRT_SECURE_NO_WARNINGS -o jsonmergetest.exe jsonmergetest.c ../c/json.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c

      - name: 'run jstest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang++ -c ../platform/windows/cppregex.cpp ../platform/windows/winregex.cpp
          clang -I ../../quickjs/porting -I../../deps/include -I../platform/windows -I ../../quickjs -I ..\h -DCONFIG_VERSION=\"2021-03-27\" -D_CRT_SECURE_NO_WARNINGS -Dstrdup=_strdup -DYAML_VERSION_MAJOR=0 -DYAML_VERSION_MINOR=2 -DYAML_VERSION_PATCH=5 -DYAML_VERSION_STRING=\"0.2.5\" -DYAML_DECLARE_STATIC=1 -Wdeprecated-declarations --rtlib=compiler-rt -o jstest.exe jstest.c ../../quickjs/quickjs.c ../../quickjs/cutils.c ../../quickjs/quickjs-libc.c ../../quickjs/libbf.c ./../quickjs/libregexp.c ./../quickjs/libunicode.c ./../quickjs/porting\winpthread.c ./../quickjs/porting\wintime.c ./../quickjs/porting\windirent.c ./../quickjs/porting\winunistd.c ./../quickjs/repl.c ../../deps/src/api.c ../../deps/src/reader.c ../../deps/src/scanner.c ../../deps/src/parser.c ../../deps/src/loader.c ../../deps/src/writer.c ../../deps/src/emitter.c ../../deps/src/dumper.c ../c/yaml2json.c ../c/embeddedjs.c ../c/jsonschema.c ../c/json.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c cppregex.o winregex.o ../platform/windows/winfile.c
          
      
      - name: 'run parsetest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang -I../h -I../platform/windows -D_CRT_SECURE_NO_WARNINGS -Dstrdup=_strdup -DYAML_DECLARE_STATIC=1 -Wdeprecated-declarations --rtlib=compiler-rt -o parsetest.exe parsetest.c ../c/parsetools.c ../c/json.c ../c/winskt.c ../c/xlate.c ../c/charsets.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c

      - name: 'run pattest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang++ -c ../platform/windows/cppregex.cpp ../platform/windows/winregex.cpp
          clang -I../../deps/include -I./src -I../h -I ../platform/windows -Dstrdup=_strdup -D_CRT_SECURE_NO_WARNINGS -DYAML_VERSION_MAJOR=0 -DYAML_VERSION_MINOR=2 -DYAML_VERSION_PATCH=5 -DYAML_VERSION_STRING=\"0.2.5\" -DYAML_DECLARE_STATIC=1 -o pattest.exe pattest.c ../c/timeutls.c ../c/utils.c ../c/alloc.c cppregex.o winregex.o


      - name: 'run qjstest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang++ -c ../platform/windows/cppregex.cpp ../platform/windows/winregex.cpp
          clang -I ../../quickjs/porting -I../../deps/include -I ../../quickjs -I./src -I../h -I ../platform/windows -DCONFIG_VERSION=\"2021-03-27\" -DCONFIG_BIGNUM=1 -Dstrdup=_strdup -D_CRT_SECURE_NO_WARNINGS -DYAML_VERSION_MAJOR=0 -DYAML_VERSION_MINOR=2 -DYAML_VERSION_PATCH=5 -DYAML_VERSION_STRING=\"0.2.5\" -DYAML_DECLARE_STATIC=1 --rtlib=compiler-rt -o qjstest.exe qjstest.c ../c/embeddedjs.c ../../quickjs/quickjs.c ../../quickjs/cutils.c ../../quickjs/quickjs-libc.c ../../quickjs/libbf.c ../../quickjs/libregexp.c ../../quickjs/libunicode.c ../../quickjs/porting\winpthread.c ../../quickjs/porting\wintime.c ../../quickjs/porting\windirent.c ../../quickjs/porting\winunistd.c ../../deps/src/api.c ../../deps/src/reader.c ../../deps/src/scanner.c ../../deps/src/parser.c ../../deps/src/loader.c ../../deps/src/writer.c ../../deps/src/emitter.c ../../deps/src/dumper.c ../c/yaml2json.c ../c/microjq.c ../c/parsetools.c ../c/jsonschema.c ../c/json.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c ../platform/windows/winfile.c cppregex.o winregex.o

      
      - name: 'run schematest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          clang++ -c ../platform/windows/cppregex.cpp ../platform/windows/winregex.cpp
          clang -I../../deps/include -I./src -I../h -I ../platform/windows -Dstrdup=_strdup -D_CRT_SECURE_NO_WARNINGS -DYAML_VERSION_MAJOR=0 -DYAML_VERSION_MINOR=2 -DYAML_VERSION_PATCH=5 -DYAML_VERSION_STRING=\"0.2.5\" -DYAML_DECLARE_STATIC=1 -o schematest.exe schematest.c ../../deps/src/api.c ../../deps/src/reader.c ../../deps/src/scanner.c ../../deps/src/parser.c ../../deps/src/loader.c ../../deps/src/writer.c ../../deps/src/emitter.c ../../deps/src/dumper.c ../c/yaml2json.c ../c/jsonschema.c ../c/json.c ../c/xlate.c ../c/charsets.c ../c/winskt.c ../c/logging.c ../c/collections.c ../c/timeutls.c ../c/utils.c ../c/alloc.c cppregex.o winregex.o


      - name: 'run setkeytest.c'
        continue-on-error: true
        run: |
          cd zowe-common-c/tests
          xlclang -q64 -D_OPEN_SYS_FILE_EXT=1 -D_XOPEN_SOURCE=600 -D_OPEN_THREADS=1 -DSUBPOOL=132 "-Wc,float(ieee),longname,langlvl(extc99),gonum,goff,ASM,asmlib('CEE.SCEEMAC','SYS1.MACLIB','SYS1.MODGEN')" "-Wl,ac=1" -I ../h -I ../platform/posix -Wbitwise-op-parentheses -o setkeytest setkeytest.c ../c/zos.c ../c/timeutls.c ../c/utils.c ../c/alloc.c 

